### ISSUE TITLE
Can't get snapshot test to fail

### ISSUE THREAD

**Issue by 0xR** [suchipi/chai-jest-snapshot#1]
For some reason my snapshot always gets updated and my test will remain green. It does not matter whether I pass true to the matcher or don't.

I'm using 0.1.1 and I'm continuing investigating what is going on.

**Comment by 0xR** [comment]
The issue occurs when passing a relative url. Passing an absolute url by wrapping the filename in `path.resolve` fixes the issue. In my environment `__dirname` is a relative url because it was passed through webpack.

**Comment by 0xR** [comment]
One possible cause could be that `chai-jest-snapshot` does not resolve the file with relative url when checking if it exists. When it doesn't exist the default behavior is to create a snapshot file. This overwrites the file that was there initially.

**Comment by suchipi** [comment]
Thanks for the bug report.

I'm thinking that I'll make a change to resolve all relative paths passed in. Can you think of any negative side effects in doing this? Rather, could this impact your testing environment negatively?

**Comment by suchipi** [comment]
This should be fixed in 0.1.2.

**Comment by 0xR** [comment]
Admittedly I only wrote 1 test to check whether it works. 

But from a DX perspective it would be nice to be able to pass in a relative url which is relative to the current test file instead of the current working directory.

For example:
In file `test/components/mycomponent-spec.js` I want to pass in `snapshots/mycomponent.js.snap` this should then create `test/components/snapshots/mycomponents.js.snap` instead of `myproject/snapshots/mycomponents.js.snap`. 

However trying to implement that would add some magic to this library because you would have to resolve the location of the calling file by using a stacktrace or something.

Therefore I reckon the current solution also works.

**Comment by suchipi** [comment]
Yeah. I tried to implement it relative to current test file at first, but realized I would have to add some magic that wouldn't always do what was wanted (for example, all my tests for this package are run through webpack first, so they're actually executed from a different folder from where the source code is. However, I want my snapshots to be stored with my source code, not in my build output directory. If I tried to determine test location at runtime, they would end up in the wrong place). 

For what it's worth, eventually I hope to make packages that integrate this assertion helper more closely with test runners, namely mocha. Those may be able to have a better DX because I can safely make more assumptions about the environment.
