### ISSUE TITLE
Using Jest Snapshot 19.0

### ISSUE THREAD

**Issue by tomatau** [suchipi/chai-jest-snapshot#10]
Are there any plans to upgrade the version of jest-snapshot? I can see their API has changed quite a bit so it would involve potentially a bigger rewrite.

I ask because a feature like serializers would be really useful and I can see they aren't supported in v14 which it looks like you're using right now.

**Comment by suchipi** [comment]
Yeah, I want to do that but have not yet.

I was following the API changes through version 17 or so and I think that everything we are doing in this package will still be possible. There are also large parts of it that should be deferrable to `jest-snapshot` itself that I had to partially duplicate here when I wrote it against version 14.

The update to `chai-jest-snapshot` to use the latest `jest-snapshot` will be a breaking change because the snapshot format will have changed, but my hope is that the only breaking change will be the snapshot format.

As far as snapshot serialization goes, I will probably have to add a new method to the main export of `chai-jest-snapshot` that lets you configure it, but I am interested in supporting that feature.

**Comment by tomatau** [comment]
It looks like they've baked in the matchesSnapshot assertion so most can be deferred to that method directly which I'm guessing is what you were saying too!

It would make sense to encourage consumers to just depend on jest-snapshot directly when they wish to add customisations as most APIs for adding serializers etc are already on there

**Comment by suchipi** [comment]
Ah, you're right. Yeah, `require('jest-snapshot').addSerializer` would work just fine.

**Comment by leanne1** [comment]
I would also really like to see an update to jest-snaphot >= v19. I am experiencing issues with quote character escaping as described in this jest issue: https://github.com/facebook/jest/issues/1789. It was fixed in v 19 of jest. I have had to disable some chai-jest-snapshot tests on account of this bug. So it would be great if you could please update soon!

**Comment by suchipi** [comment]
`chai-jest-snapshot@1.0.0` now uses `jest-snapshot@20.0.3`. Jest's snapshot format has changed, which is why this was a major version bump (from 0.4.0 to 1.0.0). You will need to update all your snapshots after updating to this version.
