### ISSUE TITLE
Function names missing as of 1.0.0

### ISSUE THREAD

**Issue by fadookie** [suchipi/chai-jest-snapshot#15]
Hello,
We noticed that after upgrading to v1.0.0, names of functions are now missing. For instance, where v0.3.0 would render `[Function toolboxPressed]`, 1.0.0 just renders `[Function]` for any function props.

Was this change intentional, and if so, what was the rationale? It seems like this makes snapshots less valuable for verifying if callback wiring has changed.

**Comment by suchipi** [comment]
v1.0.0 upgraded jest-snapshot from version 14 to version 20.0.3. I expected this to change the snapshot format slightly (which is why it was a major version bump), but am surprised that function names are no longer appearing.

@cpojer or @dmitriiabramov or @thymikee can you advise? I looked for a snapshot in jest's integration tests that I could go through the history of to find when this behavior changed, but couldn't find any integration tests around snapshots of react components with named function properties.

@fadookie if you could provide a minimal reproduction repo that we can `git clone` and `npm test`, that would help expedite a fix for this issue. In the meantime, you can find all the functionality present in v1.0.0 *except* for the snapshot format change in v0.4.0.

**Comment by cpojer** [comment]
Function names aren't stable across node versions, especially 4 and 6, where 6 has a better way to infer function names, like `const foo = () => {}` will make `foo.name` be `foo`. Second, with code coverage, this name inference would almost always break. We had a lot of people report flakiness, so we dropped it.

**Comment by suchipi** [comment]
Thanks for the explanation. Could a user who desires function names in their snapshots (for whom the difference between node versions and problems with coverage are acceptable) get them by writing a custom snapshot serializer?

**Comment by suchipi** [comment]
@fadookie I have written a snapshot serializer which restores function names: [jest-snapshot-serializer-function-name](https://www.npmjs.com/package/jest-snapshot-serializer-function-name)

To add it to chai-jest-snapshot, update to version 1.1.0 or higher, install that package, then:
```
chaiJestSnapshot.addSerializer(require("jest-snapshot-serializer-function-name"))
```
