### ISSUE TITLE
Support CI flag introduced by Jest 20

### ISSUE THREAD

**Issue by jhuiting** [suchipi/chai-jest-snapshot#18]
We've been using the library for a while now (and are quite happy about it 👍 )  but are facing some issues on the CI with snapshot files. This happens e.g. when someone forgets to add a scenario to a snapshot file or forgets commiting a snapshot file at all. I found out that Jest 20 supports the `--ci` flag, would it be possible to add support in this library as well? I can help adding this feature but wasn't entirely sure where to start.

**Comment by suchipi** [comment]
Yeah, we should do this. It should probably be implemented using a `CI=true` environment variable. `jest-snapshot` exposes the piece that controls this functionality, so it shouldn't be too hard to implement; we should:

* Add a check for the `CI` environment variable to [determineConfig](https://github.com/suchipi/chai-jest-snapshot/blob/master/src/determineConfig.js) and return it as a property in the returned object from that function
* Destructure this property in buildMatchSnapshot and when it is true, pass `updateSnapshot` as `"none"` to the SnapshotState constructor: [buildMatchSnapshot](https://github.com/suchipi/chai-jest-snapshot/blob/9322c6fabe999fc8abf042821e5f61e558484272/src/buildMatchSnapshot.js#L17)
* Expand [the determineConfig spec](https://github.com/suchipi/chai-jest-snapshot/blob/master/src/spec/determineConfig.spec.js) to check for the ci flag

If you want to make a PR with these changes, I'd gladly accept it. Otherwise, I will try to implement these changes this weekend.

**Comment by jhuiting** [comment]
@suchipi Thanks for the clear pointers, I've opened a PR with the suggested changes

**Comment by jhuiting** [comment]
Fixed by #19

**Comment by suchipi** [comment]
Thank you for the PR!

**Comment by jhuiting** [comment]
No worries, thanks for your help!

**Comment by suchipi** [comment]
This has been released as part of `1.2.0`
